import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1 },
  fixedCategories: {
    position: 'absolute',
    top: 158,
    left: 0,
    right: 0,
    zIndex: 10,
    paddingVertical: 12,
  },
  headerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  toggleButton: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 12 },
  toggleButtonText: { fontWeight: '700', fontSize: 14 },
  createButton: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 12 },
  createButtonText: { color: '#fff', fontWeight: '700' },
  subtitleText: { fontSize: 14, marginBottom: 12 },
  categoryScroll: { marginBottom: 0 },
  categoryButton: { paddingVertical: 8, paddingHorizontal: 14, borderRadius: 12 },
  templateCard: { 
    borderRadius: 16, 
    padding: 16, 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  templateTitle: { fontSize: 16, fontWeight: '700', marginBottom: 4 },
  templateCategory: { fontSize: 12, fontWeight: '500' },
  adminBadge: { 
    backgroundColor: '#FEF3C7', 
    paddingHorizontal: 8, 
    paddingVertical: 2, 
    borderRadius: 8, 
    marginLeft: 8 
  },
  adminBadgeText: { 
    color: '#92400E', 
    fontSize: 10, 
    fontWeight: '700' 
  },
  useButton: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 12 },
  useButtonText: { color: '#fff', fontWeight: '700' },
  loadingOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 32,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    minWidth: 200,
  },
  loadingTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    marginTop: 16,
    marginBottom: 8,
  },
  loadingText: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
  },
  holdOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  swipeActionBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
  },
  swipeAction: {
    flex: 1,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
  },
  editActionBg: {
    backgroundColor: '#4F46E5',
  },
  deleteActionBg: {
    backgroundColor: '#EF4444',
  },
  swipeActionText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 14,
  },
  swipeHintContainer: {
    position: 'absolute',
    bottom: 8,
    left: 0,
    right: 0,
    alignItems: 'center',
    paddingHorizontal: 8,
  },
  swipeHint: {
    fontSize: 11,
    color: '#FFFFFF',
    fontWeight: '600',
    textAlign: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 6,
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionButton: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 8,
    minWidth: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editButton: {
    backgroundColor: '#4F46E5',
  },
  deleteButton: {
    backgroundColor: '#EF4444',
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 14,
    textAlign: 'center',
  },
});

export default styles;
