import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'transparent',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 20,
    maxHeight: '92%',
  },
  handle: {
    width: 44,
    height: 5,
    backgroundColor: '#D1D5DB',
    borderRadius: 999,
    alignSelf: 'center',
    marginBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: '800',
    textAlign: 'center',
    color: '#111827',
  },
  subtitle: {
    textAlign: 'center',
    color: '#6B7280',
    marginBottom: 20,
  },
  aiRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 20,
  },
  aiButton: {
    flex: 1,
    backgroundColor: '#6366F1',
    padding: 14,
    borderRadius: 14,
  },
  aiButtonAlt: {
    flex: 1,
    backgroundColor: '#EEF2FF',
    padding: 14,
    borderRadius: 14,
  },
  aiText: {
    color: '#fff',
    fontWeight: '700',
    textAlign: 'center',
  },
  aiTextAlt: {
    color: '#4338CA',
    fontWeight: '700',
    textAlign: 'center',
  },
  // Enhanced Hashtag Section Styles
  hashtagSection: {
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    padding: 16,
    marginTop: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  hashtagHeader: {
    marginBottom: 16,
  },
  hashtagTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  hashtagTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
  },
  hashtagCountBadge: {
    backgroundColor: '#6366F1',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginLeft: 8,
  },
  hashtagCountText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  hashtagSubtitle: {
    fontSize: 13,
    color: '#6B7280',
    marginTop: 2,
  },
  hashtagInputContainer: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  hashtagInputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderRadius: 12,
    paddingHorizontal: 12,
  },
  hashtagInputIcon: {
    marginRight: 8,
  },
  hashtagInput: {
    flex: 1,
    paddingVertical: 12,
    fontSize: 15,
    color: '#111827',
  },
  hashtagAddButton: {
    backgroundColor: '#6366F1',
    width: 48,
    height: 48,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#6366F1',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  selectedHashtagsContainer: {
    marginBottom: 16,
  },
  selectedHashtagsLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#6B7280',
    marginBottom: 8,
  },
  selectedHashtagsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  hashtagChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    paddingLeft: 10,
    paddingRight: 6,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1.5,
    borderColor: '#6366F1',
    shadowColor: '#6366F1',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  hashtagChipContent: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 4,
  },
  hashtagChipText: {
    color: '#4338CA',
    fontWeight: '600',
    fontSize: 14,
  },
  hashtagRemoveButton: {
    padding: 2,
  },
  aiHashtagButton: {
    backgroundColor: '#10B981',
    padding: 14,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  aiHashtagButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  aiHashtagButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 15,
  },
  suggestionsSection: {
    backgroundColor: '#FFFBEB',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#FDE68A',
  },
  suggestionsTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  suggestionsTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: '#92400E',
  },
  suggestionsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  suggestionChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F3E8FF',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#D8B4FE',
  },
  suggestionChipText: {
    color: '#6B21A8',
    fontWeight: '600',
    fontSize: 13,
  },
  section: {
    fontSize: 16,
    fontWeight: '700',
    marginTop: 16,
    marginBottom: 8,
    color: '#111827',
  },
  pillRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  pillRowError: {
    borderWidth: 2,
    borderColor: '#EF4444',
    padding: 8,
    borderRadius: 14,
    marginBottom: 12,
  },
  pill: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#F3F4F6',
    flexDirection: 'row',
    alignItems: 'center',
  },
  pillActive: {
    backgroundColor: '#6366F1',
  },
  pillText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  pillTextActive: {
    color: '#fff',
  },
  input: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    padding: 14,
    fontSize: 16,
    marginBottom: 12,
    backgroundColor: '#FAFBFC',
    color: '#111827',
  },
  inputError: {
    borderColor: '#EF4444',
    borderWidth: 2,
    backgroundColor: '#FEE2E2',
    shadowColor: '#DC2626',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 5,
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  textAreaExpanded: {
    height: 300,
    textAlignVertical: 'top',
  },
  hashtagRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  add: {
    backgroundColor: '#6366F1',
    paddingHorizontal: 16,
    borderRadius: 12,
    justifyContent: 'center',
  },
  addText: {
    color: '#fff',
    fontWeight: '700',
  },
  tagWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 20,
  },
  tag: {
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
  },
  tagText: {
    color: '#4338CA',
    fontWeight: '600',
  },
  errorText: {
    color: '#DC2626',
    fontSize: 12,
    fontWeight: '600',
    marginTop: -8,
    marginBottom: 8,
  },
  suggestionsContainer: {
    maxHeight: 150,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    marginBottom: 12,
  },
  suggestionsList: {
    padding: 10,
  },
  suggestionItem: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  suggestionText: {
    fontSize: 16,
    color: '#374151',
  },
  primary: {
    backgroundColor: '#6366F1',
    padding: 16,
    borderRadius: 16,
    marginBottom: 10,
  },
  primaryText: {
    color: '#fff',
    fontWeight: '800',
    textAlign: 'center',
    fontSize: 16,
  },
  secondary: {
    padding: 14,
  },
  secondaryText: {
    textAlign: 'center',
    color: '#6B7280',
    fontWeight: '600',
  },
  uploadButton: {
    backgroundColor: '#EEF2FF',
    padding: 14,
    borderRadius: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  uploadText: {
    color: '#4338CA',
    fontWeight: '700',
    textAlign: 'center',
  },
  imageContainer: {
    marginBottom: 12,
  },
  imageWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    padding: 10,
    borderRadius: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  imageUri: {
    flex: 1,
    fontSize: 14,
    color: '#374151',
  },
  onlineSearchRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 12,
  },
  onlineSearchInput: {
    flex: 1,
    marginBottom: 0,
  },
  onlineSearchButton: {
    backgroundColor: '#111827',
    paddingHorizontal: 16,
    borderRadius: 12,
    justifyContent: 'center',
  },
  onlineSearchButtonText: {
    color: '#fff',
    fontWeight: '700',
  },
  onlineResultsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 12,
  },
  onlineImageCard: {
    width: '48%',
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#F9FAFB',
  },
  onlineImage: {
    width: '100%',
    height: 120,
  },
  onlineImageOverlay: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    backgroundColor: 'rgba(17, 24, 39, 0.8)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  onlineImageOverlayText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  onlineImageMeta: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#F9FAFB',
  },
  onlineImageMetaText: {
    fontSize: 12,
    color: '#6B7280',
    fontWeight: '600',
  },
  unsplashAttribution: {
    alignSelf: 'flex-start',
    marginBottom: 12,
  },
  unsplashAttributionText: {
    fontSize: 12,
    color: '#111827',
    textDecorationLine: 'underline',
    fontWeight: '600',
  },
  urlRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
    alignItems: 'center',
  },
  urlInputWrapper: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#E5E7EB',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  urlInputIcon: {
    marginRight: 10,
  },
  urlInput: {
    flex: 1,
    fontSize: 15,
    color: '#374151',
    paddingVertical: 12,
  },
  pasteButton: {
    backgroundColor: '#F0F9FF',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#0EA5E9',
    flexDirection: 'row',
    gap: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 1,
  },
  pasteText: {
    color: '#0284C7',
    fontWeight: '700',
    fontSize: 14,
  },
  addUrlButton: {
    backgroundColor: '#10B981',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
  },
  addUrlText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 14,
  },
  urlContainer: {
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  urlWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0F9FF',
    padding: 14,
    borderRadius: 12,
    marginBottom: 10,
    borderWidth: 2,
    borderColor: '#BAE6FD',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 3,
    elevation: 2,
  },
  urlTextWrapper: {
    flex: 1,
    marginRight: 10,
  },
  urlText: {
    flex: 1,
    fontSize: 13,
    color: '#0C4A6E',
    fontWeight: '500',
  },
  urlOpenButton: {
    marginLeft: 8,
    backgroundColor: '#0284C7',
    borderRadius: 10,
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#0284C7',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 2,
  },
  removeButton: {
    marginLeft: 8,
    backgroundColor: '#FEE2E2',
    borderRadius: 10,
    width: 36,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FECACA',
    shadowColor: '#DC2626',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 1,
  },
  removeText: {
    color: '#DC2626',
    fontWeight: 'bold',
    fontSize: 20,
  },
  removeTagButton: {
    marginLeft: 6,
    backgroundColor: '#EF4444',
    borderRadius: 999,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeTagText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
  },
  actionButtons: {
    marginBottom: 16,
  },
  createPostButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#10B981',
    paddingVertical: 16,
    borderRadius: 12,
    marginBottom: 12,
    gap: 8,
  },
  createPostButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  saveDraftButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    paddingVertical: 14,
    borderRadius: 12,
    marginBottom: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: '#D1D5DB',
  },
  saveDraftButtonText: {
    color: '#6B7280',
    fontSize: 16,
    fontWeight: '600',
  },
  facebookButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1877F2',
    paddingVertical: 14,
    borderRadius: 12,
    marginBottom: 12,
    gap: 8,
  },
  facebookButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  instagramButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E4405F',
    paddingVertical: 14,
    borderRadius: 12,
    marginBottom: 12,
    gap: 8,
  },
  instagramButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  facebookShareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    paddingVertical: 14,
    borderRadius: 12,
    marginBottom: 12,
    gap: 8,
    borderWidth: 2,
    borderColor: '#1877F2',
  },
  facebookShareButtonText: {
    color: '#1877F2',
    fontSize: 16,
    fontWeight: '700',
  },
  nativeShareButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F3F4F6',
    paddingVertical: 14,
    borderRadius: 12,
    marginBottom: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: '#D1D5DB',
  },
  nativeShareButtonText: {
    color: '#374151',
    fontSize: 16,
    fontWeight: '600',
  },
  imageTouchable: {
    flex: 1,
  },
  imageViewerOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageViewerClose: {
    position: 'absolute',
    top: 50,
    right: 20,
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  imageViewerCloseText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  imageViewerNav: {
    position: 'absolute',
    top: '50%',
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 25,
    width: 50,
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  imageViewerNavLeft: {
    left: 20,
  },
  imageViewerNavRight: {
    right: 20,
  },
  imageViewerNavText: {
    color: '#fff',
    fontSize: 24,
    fontWeight: 'bold',
  },
  imageViewerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  imageViewerImage: {
    width: '90%',
    height: '70%',
    borderRadius: 10,
  },
  imageViewerCounter: {
    position: 'absolute',
    bottom: 50,
    backgroundColor: 'rgba(0,0,0,0.7)',
    color: '#fff',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    fontSize: 16,
    fontWeight: '600',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 8,
  },
  viewFullButton: {
    backgroundColor: '#6366F1',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  viewFullText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
  },
  fullContentOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  fullContentContainer: {
    backgroundColor: '#fff',
    borderRadius: 20,
    width: '100%',
    maxHeight: '80%',
    overflow: 'hidden',
  },
  fullContentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  fullContentTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
  },
  fullContentClose: {
    backgroundColor: '#F3F4F6',
    borderRadius: 20,
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  fullContentCloseText: {
    color: '#374151',
    fontSize: 18,
    fontWeight: 'bold',
  },
  fullContentScroll: {
    padding: 20,
    maxHeight: '70%',
  },
  fullContentText: {
    fontSize: 16,
    lineHeight: 24,
    color: '#111827',
  },
  fullContentFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  fullContentCount: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '600',
  },
  fullContentButton: {
    backgroundColor: '#6366F1',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 12,
  },
  fullContentButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 15,
  },
  loadingOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 32,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    minWidth: 200,
  },
  loadingTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
    marginTop: 16,
    marginBottom: 8,
  },
  loadingText: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
  },
  floatingBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'flex-end',
  },
  floatingResultsContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 20,
    paddingHorizontal: 16,
    paddingBottom: 24,
    maxHeight: '85%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 12,
  },
  floatingHeaderContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  floatingCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
  },
  floatingCloseButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#6B7280',
  },
  floatingResultsHeader: {
    marginBottom: 16,
  },
  floatingResultsTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
  },
  floatingResultsScroll: {
    flex: 1,
    maxHeight: 400,
  },
  floatingResultsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    paddingBottom: 12,
  },
  floatingImageCard: {
    width: '31%',
    aspectRatio: 1,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#F3F4F6',
    position: 'relative',
  },
  floatingImage: {
    width: '100%',
    height: '100%',
  },
  floatingImageAddButton: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(17, 24, 39, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0,
  },
  floatingImageAddButtonText: {
    fontSize: 32,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  floatingAttribution: {
    alignSelf: 'flex-start',
    marginTop: 12,
    paddingVertical: 8,
  },
  floatingAttributionText: {
    fontSize: 12,
    color: '#6B7280',
    textDecorationLine: 'underline',
    fontWeight: '600',
  },
  // Inline expandable image results (new approach)
  inlineImageResultsContainer: {
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    marginTop: 12,
    marginBottom: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    overflow: 'hidden',
    maxHeight: 400,
  },
  inlineResultsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  inlineResultsTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    flex: 1,
  },
  inlineCloseButton: {
    padding: 4,
    marginLeft: 8,
  },
  inlineImageScroll: {
    marginHorizontal: -16,
    marginBottom: 8,
  },
  inlineImageScrollContent: {
    paddingHorizontal: 16,
    gap: 12,
  },
  inlineImageCard: {
    width: 200,
    height: 200,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#E5E7EB',
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  inlineImageCardFirst: {
    marginLeft: 0,
  },
  inlineImageCardLast: {
    marginRight: 0,
  },
  inlineImage: {
    width: '100%',
    height: '100%',
  },
  inlineImageOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(99, 102, 241, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  inlineImageAddIcon: {
    backgroundColor: 'rgba(99, 102, 241, 0.9)',
    borderRadius: 999,
    padding: 2,
  },
  inlineImagePhotographer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.75)',
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  inlineImagePhotographerText: {
    fontSize: 11,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  inlineUnsplashAttribution: {
    alignSelf: 'flex-start',
    paddingVertical: 6,
    paddingHorizontal: 4,
    marginTop: 4,
  },
  inlineUnsplashAttributionText: {
    fontSize: 11,
    color: '#6B7280',
    textDecorationLine: 'underline',
    fontWeight: '600',
  },
});

